# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  branches:
    release:
      - step: &Push-to-GitHub
          name: Push code changes to GitHub
          services:
            - docker
          caches:
            - docker
          script:
            - git config --global user.name louai5228
            - git config --global user.email louai5228@gmail.com
            - git init
            - git remote add github https://github.com/louai5228/abraa-staging.git
            - git checkout release
            - git push -f github release

definitions:
  services:
    docker:
      memory: 1024


