# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  branches:
    release:
      - step:
          name: "Build"
          script:
            - npm install
            - npm run-script build
          caches:
            - "node"
      - step:
          name: "Build and push to github"
          script:
            - apt-get update
            - apt install --assume-yes --no-install-recommends git openssh-client
            - git config --global user.name louai5228
            - git config --global user.email louai5228@gmail.com
            - cd release
            - git init
            - git remote add github https://github.com/louai5228/abraa-staging.git
            - git checkout -b staging
            - git add .
            - git commit -m "Added new version of at $(date)"
            - git push -f github _build

definitions:
  services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: 'homestead'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USER: 'homestead'
        MYSQL_PASSWORD: 'secret'
