# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  branches:
    release:
      - step: &Push-to-GitHub
          name: Push code changes to GitHub
          services:
            - docker
          caches:
            - docker
          script:
            - git remote add github "git@github.com:[yourname]/[your repo].git"
            - git checkout $BITBUCKET_BRANCH
            - git pull
            - git push github $BITBUCKET_BRANCH

definitions:
  services:
    docker:
      memory: 1024


