image: php:8.0
pipelines:
  branches:
    ewallet-staging:
      - step:
          caches:
            - composer
          script:
            - apt-get update && apt-get install -qy git zip curl libmcrypt-dev default-mysql-client libxml2-dev default-jre wget maven
            - yes | pecl install mcrypt-1.0.4
            - docker-php-ext-install pdo_mysql bcmath
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - ln -f -s .env.pipelines .env
            - composer install
            - php artisan migrate
            - php artisan serve &
            - sleep 5
            - php vendor/phpunit/phpunit/phpunit
            - curl -vk http://localhost:8000
            - apt-get -qq install git-ftp
            - git ftp push --user $EWALLET_STAGING_FTP_USERNAME --passwd $EWALLET_STAGING_FTP_PASSWORD $EWALLET_STAGING_FTP_HOST
          services:
            - mysql

definitions:
  services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: 'homestead'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USER: 'homestead'
        MYSQL_PASSWORD: 'secret'
