image: php:8.0
pipelines:
  branches:
    dev:
      - step:
          caches:
            - composer
          script:
            - apt-get update && apt-get install -qy git zip curl libmcrypt-dev default-mysql-client libxml2-dev default-jre wget maven
            - yes | pecl install mcrypt-1.0.4
            - docker-php-ext-install pdo_mysql bcmath
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - ln -f -s .env.pipelines .env
            - composer install --ignore-platform-reqs
            - php artisan migrate
            - php artisan serve &
            - sleep 5
            - php vendor/phpunit/phpunit/phpunit
            - curl -vk http://localhost:8000
            - apt-get -qq install git-ftp
            - echo $APP_ENV | base64 --decode --ignore-garbage > .env
            - git add .
            - git commit -m "overide .env file"
            - git ftp push --user $DEV_FTP_USERNAME --passwd $DEV_FTP_PASSWORD $DEV_FTP_HOST
          artifacts: # defining the artifacts to be passed to each future step.
            - vendor/
            - .env
          services:
            - mysql
    master:
      - step:
          caches:
            - composer
          script:
            - mkdir /usr/share/man/users_service/
            - apt-get update && apt-get install -qy git zip curl libmcrypt-dev default-mysql-client libxml2-dev default-jre wget maven
            - yes | pecl install mcrypt-1.0.4
            - docker-php-ext-install pdo_mysql bcmath
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - ln -f -s .env.pipelines .env
            - composer install
            - php artisan migrate
            - php artisan serve &
            - sleep 5
            - php vendor/phpunit/phpunit/phpunit
            - curl -vk http://localhost:8000

          services:
            - mysql

definitions:
  services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: 'homestead'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USER: 'homestead'
        MYSQL_PASSWORD: 'secret'
